name: sync-resource

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-reource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: Cryolitia

      - name: Checkout Remote
        uses: actions/checkout@v4
        with:
          repository: Cryolitia/Cryolitia.github.io
          show-progress: false
          ssh-key: ${{secrets.SSH_KEY}}
          path: Cryolitia.github.io

      - name: Setup Git
        run: |
          cd Cryolitia.github.io
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git show -s
          cd ..

      - name: Update
        run: |
          export commit_msg=$(git show -s --format=%s)
          shopt -s extglob

          rm -rf Cryolitia/.github
          cp -rf Cryolitia/* Cryolitia.github.io/

          cd Cryolitia.github.io
          git add .
          git status
          git commit -m "$commit_msg" || exit 0
          git push
